# Generated by Django 3.2.4 on 2024-06-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20240617_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
